project_id = "gneoaocemmuanbzdnorc"

[api]
enabled = true
port = 54321
schemas = ["public", "auth"]

[db]
port = 54322
major_version = 17

[auth]
enabled = true
site_url = "http://localhost:3000"

[auth.email]
enable_signup = true
enable_confirmations = false

[studio]
enabled = true
port = 54323
